/**
 * The typed RpcGroup for herdr's socket protocol.
 *
 * Sketch — the real contract enumerates all 85 methods from
 * `scripts/herdr-schema.json`. Full curation is a deferred grilling item.
 * Shown here: one of each of the four RPC shapes so the sketch demonstrates
 * the range and confirms the four-shape enumeration from D3.
 */


// TODO(schema-codegen): every payload / success / stream-element / stream-error
// type below is currently `unknown` — real Schema.Struct{...} definitions get
// generated by walking herdr-schema.json.

export declare const HerdrRpcs: unknown /*
  RpcGroup.RpcGroup<
    // -- request/reply ------------------------------------------------------
    | Rpc.Rpc<"pane.get",     { paneId: PaneId },        Pane,                    HerdrProtocolError>
    | Rpc.Rpc<"pane.list",    { workspaceId: WorkspaceId }, Schema.Array<Pane>,   HerdrProtocolError>
    | Rpc.Rpc<"pane.current", void,                      Pane,                    HerdrProtocolError>
    | Rpc.Rpc<"tab.get",      { tabId: TabId },          Tab,                     HerdrProtocolError>
    | Rpc.Rpc<"workspace.get",{ workspaceId: WorkspaceId }, Workspace,            HerdrProtocolError>
    | Rpc.Rpc<"workspace.list", void,                    Schema.Array<Workspace>, HerdrProtocolError>
    | Rpc.Rpc<"pane.split",   PaneSplitPayload,          Pane,                    HerdrProtocolError>
    | Rpc.Rpc<"pane.focus",   { paneId: PaneId },        Schema.Void,             HerdrProtocolError>
    | Rpc.Rpc<"session.snapshot", void,                  SessionSnapshot,         HerdrProtocolError>

    // -- fire-and-forget (caller uses { discard: true }) --------------------
    | Rpc.Rpc<"pane.send_text", { paneId: PaneId; text: string }, Schema.Void, HerdrProtocolError>
    | Rpc.Rpc<"pane.send_keys", { paneId: PaneId; keys: string  }, Schema.Void, HerdrProtocolError>

    // -- streaming ----------------------------------------------------------
    | Rpc.Rpc<"pane.wait_for_output", WaitPayload,       RpcSchema.Stream<OutputChunk, WaitError>, HerdrProtocolError>
    | Rpc.Rpc<"events.subscribe",     EventsSubscribePayload, RpcSchema.Stream<HerdrEvent, never>, HerdrProtocolError>

    // ... 73 more, generated from schema ...
  >
*/
